"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from .env import Env
from pathlib import Path
from datetime import timedelta
from django.core.management.commands.runserver import Command as runserver

# Cambiando el host a 0.0.0.0 para poder acceder desde afuera del contenedor
runserver.default_addr = "0.0.0.0"

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = Env.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = Env.DEBUG

ALLOWED_HOSTS = Env.ALLOWED_HOSTS  # ["*"]


# Application definition
SHARED_APPS = [
    "colegio",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",  # permite relacion de tablas por GenericForeignKey
    "django.contrib.sessions",  # sesion de usuarios (cookies)
    "django.contrib.messages",  # mensajes temporales “Usuario creado correctamente” después de un POST.
    "django.contrib.staticfiles",  # Gestionar archivos estaticos
]

TENANT_APPS = [
    "tenant",  # app de tenants
    "django.contrib.auth",  # usuarios y permisos por tenant
    "django.contrib.admin",  # admin por tenant
    "django.contrib.sessions",  # sesiones por tenant
]

THIRD_APPS = [
    "django_tenants",
    "corsheaders",
    "rest_framework",
    "django_extensions",
    "drf_spectacular",
]

COMODIN_APPS = ["core"]

INSTALLED_APPS = (
    list(SHARED_APPS)
    + [app for app in TENANT_APPS if app not in SHARED_APPS]
    + list(THIRD_APPS)
    + list(COMODIN_APPS)
)

TENANT_MODEL = "colegio.Client"

TENANT_DOMAIN_MODEL = "colegio.Domain"

MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        # "ENGINE": "django.db.backends.postgresql",
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": Env.POSTGRES_DB,
        "USER": Env.POSTGRES_USER,
        "PASSWORD": Env.POSTGRES_PASSWORD,
        "HOST": Env.POSTGRES_HOST,
        "PORT": Env.POSTGRES_PORT,
    }
}

DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# CORS_ALLOWED_ORIGINS = ["https://example.com"]
CORS_ALLOW_ALL_ORIGINS = Env.CORS_ALLOW_ALL_ORIGINS

SPECTACULAR_SETTINGS = {
    "TITLE": "Colegio API",
    "DESCRIPTION": "Sistema SaaS para colegios",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "jwtAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            },
        },
    },
    "SECURITY": [{"jwtAuth": []}],
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
        "filter": True,
    },
    "SWAGGER_UI_FAVICON_HREF": STATIC_URL + "mark.jpg",  # default is swagger favicon
    "CONTACT": {
        "name": "messi",
        "email": "email@gmai.com",
    },
    "LICENSE": {
        "name": "BSD LICENCE",
    },
    "TERMS_OF_SERVICE": "https://www.google.com/policies/terms/",
}
