FROM python:3.12-slim

# Instalar dependencias necesarias
RUN apt-get update && apt-get install -y \
  curl \
  ca-certificates \
  bash \
  build-essential
  # build-essential \
  # git

RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - 
RUN apt-get install -y nodejs

RUN python3 --version && pip3 --version && node --version && npm --version

# Instalar starship
RUN curl -sS https://starship.rs/install.sh | sh -s -- -y

RUN mkdir -p /root/.config && chown -R root:root /root/.config

COPY starship.toml /home/vscode/.config/starship.toml

COPY starship.toml /root/.config/starship.toml

RUN echo 'eval "$(starship init bash)"' >> root/.bashrc/

SHELL ["/bin/bash", "-c"]

CMD  ["bash"]
