# Generated by Django 5.2.9 on 2026-01-22 01:29

import tenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to=tenant.models.alumno_foto_path)),
            ],
        ),
    ]
