# Generated by Django 5.2.9 on 2025-12-30 14:27

import tenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=tenant.models.alumno_foto_path),
        ),
    ]
